### ISSUE TITLE
Problem with Ruby 2.0 and query_values

### ISSUE THREAD

**Issue by leifbladt** [sporkmonger/addressable#125]
``` ruby
require 'addressable/uri'
require 'net/http'

url = Addressable::URI.parse('http://www.example.com')
url.query_values = { a: '1' }

response = Net::HTTP.get_response url
p response
```

With Ruby 1.9.3 the response is as expected, with Ruby 2.0.0 a `NoMethodError` is raised (`undefined method `empty?'`)

``` bash
$ ruby -v
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.3.0]
$ ruby test.rb
#<Net::HTTPFound 302 Found readbody=true>
```

``` bash
$ ruby -v
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin12.3.0]
$ ruby test.rb
/Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http/generic_request.rb:27:in `initialize': undefined method `empty?' for #<Addressable::URI:0x3fe0dc4be52c URI:http://www.example.com?a=1> (NoMethodError)
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http/request.rb:14:in `initialize'
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1278:in `new'
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1278:in `request_get'
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:479:in `block in get_response'
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:582:in `start'
    from /Users/.../.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
    from test.rb:7:in `<main>'
```

**Comment by vfonic** [comment]
I just hit this issue with the following code:

```rb
uri = Addressable::URI.parse(API_URL + path)
uri.query_values = { 'sort_by' => 'updated_at-desc' }
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
request = Net::HTTP::Get.new(uri.to_s)
request['content-type'] = 'application/json'
response = http.request(request)
response.read_body
```

This is the code that used to work, but I needed to add the query parameter and therefore decided to switch to addressable:

```rb 

url = URI(API_URL + path)
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
request = Net::HTTP::Get.new(url)
request['content-type'] = 'application/json'
response = http.request(request)
response.read_body
```

Any idea how I can go around this issue?
One solution that comes to mind is to do:

```rb
request = Net::HTTP::Get.new(URI(uri.to_s))
```

Is there nothing simpler than this? This almost beats the purpose of using addressable if I have to manually convert back to URI instance. Wouldn't it be better if there would be some `to_uri` method or some other way that would make addressable work with net HTTP?

Thanks!
