### ISSUE TITLE
Template expansion issues with BigDecimal values

### ISSUE THREAD

**Issue by perlun** [sporkmonger/addressable#150]
[This line](https://github.com/sporkmonger/addressable/blob/master/lib/addressable/template.rb#L668) causes an exception for me, with the title mentioned above. Here is the stack trace:

```
org/jruby/ext/bigdecimal/RubyBigDecimal.java:1259:in `eql?
gems/jruby/1.9/bundler/gems/addressable-ea3c89a914d5/lib/addressable/template.rb:668:in `transform_capture'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyEnumerable.java:834:in `inject'
gems/jruby/1.9/bundler/gems/addressable-ea3c89a914d5/lib/addressable/template.rb:665:in `transform_capture'
gems/jruby/1.9/bundler/gems/addressable-ea3c89a914d5/lib/addressable/template.rb:558:in `expand'
```

The value I'm using in my Addressable template is a BigDecimal, so I presume that is related to the problem. If I change it to be a string, it works flawlessly, but this is awkward so it would be nice if wouldn't have to do it like that.

Any ideas/suggestions?

**Comment by perlun** [comment]
@sporkmonger We can probably close this now. 😉
