### ISSUE TITLE
Can not use relay address for Email (state=SSLv2/v3 read server hello A: unknown protocol")

### ISSUE THREAD

**Issue by hhimanshu** [sporkmonger/addressable#210]
This is what my `"/srv/gitlab/config/gitlab.rb"` looks like for `email` settings

    ################################
    # GitLab email server settings #
    ################################
    # see https://gitlab.com/gitlab-org/omnibus-gitlab/blob/629def0a7a26e7c2326566f0758d4a27857b52a3/doc/settings/smtp.md#smtp-settings
    # Use smtp instead of sendmail/postfix.
    
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = "corp-myorg-com.mail.outlook.com"
    gitlab_rails['smtp_port'] = 25
    # gitlab_rails['smtp_user_name'] = "smtp user"
    # gitlab_rails['smtp_password'] = "smtp password"
    # gitlab_rails['smtp_domain'] = "example.com"
    # gitlab_rails['smtp_authentication'] = "login"
    # gitlab_rails['smtp_enable_starttls_auto'] = true
    gitlab_rails['smtp_tls'] = true
    # gitlab_rails['smtp_openssl_verify_mode'] = 'none' # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
    # gitlab_rails['smtp_ca_path'] = "/etc/ssl/certs"
    # gitlab_rails['smtp_ca_file'] = "/etc/ssl/certs/ca-certificates.crt"

When I try to sign up from GitLab web page, I see in logs that  

    ==> /var/log/gitlab/gitlab-rails/production.log <==
    Started POST "/users" for 172.32.1.111 at 2015-09-10 04:50:47 +0000
    Processing by RegistrationsController#create as HTML
      Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"Harit Himanshu", "username"=>"harit", "email"=>"harit@myorg.com", "password"=>"[FILTERED]"}}
    Completed 200 OK in 364ms (Views: 44.7ms | ActiveRecord: 24.1ms)
    
    ==> /var/log/gitlab/nginx/gitlab_access.log <==
    172.32.1.111 - - [10/Sep/2015:04:50:48 +0000] "POST /users HTTP/1.1" 200 2223 "http://172.16.205.153:8080/users/sign_in" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
    
    ==> /var/log/gitlab/sidekiq/current <==
    2015-09-10_04:50:56.62636 2015-09-10T04:50:56.626Z 447 TID-elbtk Devise::Async::Backend::Sidekiq JID-24a487b2ee95a069f6783b43 INFO: start
    
    ==> /var/log/gitlab/gitlab-rails/production.log <==
    
    Sent mail to harit@myorg.com (331.0ms)
    
    ==> /var/log/gitlab/sidekiq/current <==
    2015-09-10_04:50:57.01071 2015-09-10T04:50:57.010Z 447 TID-elbtk Devise::Async::Backend::Sidekiq JID-24a487b2ee95a069f6783b43 INFO: fail: 0.384 sec
    2015-09-10_04:50:57.01139 2015-09-10T04:50:57.011Z 447 TID-elbtk WARN: {"retry"=>true, "queue"=>"mailer", "class"=>"Devise::Async::Backend::Sidekiq", "args"=>["confirmation_instructions", "User", "4", "H7fU4LytjadCSCMyJv-S", {}], "jid"=>"24a487b2ee95a069f6783b43", "enqueued_at"=>1441859975.09268, "error_message"=>"SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol", "error_class"=>"OpenSSL::SSL::SSLError", "failed_at"=>1441859975.4031353, "retry_count"=>5, "retried_at"=>1441860657.0101695}
    2015-09-10_04:50:57.01141 2015-09-10T04:50:57.011Z 447 TID-elbtk WARN: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
    2015-09-10_04:50:57.01145 2015-09-10T04:50:57.011Z 447 TID-elbtk WARN: /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:586:in `connect'
    2015-09-10_04:50:57.01146 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:586:in `tlsconnect'
    2015-09-10_04:50:57.01146 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:554:in `do_start'
    2015-09-10_04:50:57.01147 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
    2015-09-10_04:50:57.01147 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'

What is the issue, I am able to use this relay address in production with other projects.

What am I missing?

Thanks

**Comment by sporkmonger** [comment]
Nothing about this issue you're describing looks like it's cause by Addressable? I think you have the wrong project?
