### ISSUE TITLE
Another mismatch between libidn and pure Ruby punycode implementation

### ISSUE THREAD

**Issue by dentarg** [sporkmonger/addressable#239]
As you [might](https://github.com/twingly/twingly-url/issues/74#issuecomment-246395588) seen, the behaviour when normalizing differs whether you use addressable with [libidn](https://www.gnu.org/software/libidn/) or not.

Using libidn some input raises an error:

``` shell
$ BUNDLE_GEMFILE=native.Gemfile bundle exec ruby code.rb
/Users/dentarg/.gem/ruby/2.2.5/bundler/gems/addressable-a15b7045a099/lib/addressable/idna/native.rb:38:in `toASCII': Output would be too large or too small (5) (IDN::Idna::IdnaError)
    from /Users/dentarg/.gem/ruby/2.2.5/bundler/gems/addressable-a15b7045a099/lib/addressable/idna/native.rb:38:in `block in to_ascii'
    from /Users/dentarg/.gem/ruby/2.2.5/bundler/gems/addressable-a15b7045a099/lib/addressable/idna/native.rb:36:in `map'
    from /Users/dentarg/.gem/ruby/2.2.5/bundler/gems/addressable-a15b7045a099/lib/addressable/idna/native.rb:36:in `to_ascii'
    from /Users/dentarg/.gem/ruby/2.2.5/bundler/gems/addressable-a15b7045a099/lib/addressable/uri.rb:1072:in `normalized_host'
    from code.rb:4:in `<main>'
```

Using the pure Ruby implementation in Addressable there is no error:

``` shell
$ BUNDLE_GEMFILE=pure.Gemfile bundle exec ruby code.rb
"acinusfallumtrompetumnulluncreditumvisumestatcuadlongumetcefallumest.com"
```

``` ruby
$ cat code.rb
require "addressable/uri"

URL = "http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com"
p Addressable::URI.heuristic_parse(URL).normalized_host
```

[Link to directory with the `Gemfile`s used above.](https://github.com/dentarg/gists/tree/c3b854c08bfd81ed8847982ee458eeffd1af6e70/gists/addressable-issue-239) I used the current master, a15b7045a09911bcc47b106200554809c879a5f6.

**Comment by sporkmonger** [comment]
This should be resolved now.
