### ISSUE TITLE
Random segfaults

### ISSUE THREAD

**Issue by bmulholland** [sporkmonger/addressable#290]
Our CI runs (using cucumber/capybara/vcr/webmock) are crashing somewhat regularly (~5%) in the addressable gem. We just switched from the CircleCI 1.0 environment to running in a docker container on Circle 2.0 and it's still happening, so this rules out a lot of environmental possibilities.

Any suggestions on how we can investigate what might be happening?

```
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:534: [BUG] Segmentation fault at 0x000008b600000000
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0040 p:---- s:0210 e:000209 CFUNC  :initialize_dup
c:0039 p:---- s:0207 e:000206 CFUNC  :dup
c:0038 p:0256 s:0203 e:000202 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:534
c:0037 p:0033 s:0193 e:000192 BLOCK  /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1502 [FINISH]
c:0036 p:---- s:0189 e:000188 CFUNC  :map
c:0035 p:0101 s:0185 e:000184 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1501
c:0034 p:0084 s:0179 e:000175 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:2134
c:0033 p:0133 s:0172 e:000171 BLOCK  /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/util/uri.rb:20 [FINISH]
c:0032 p:0079 s:0165 e:000164 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/util/uri.rb:33
c:0031 p:0015 s:0160 e:000159 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/util/uri.rb:37
c:0030 p:0022 s:0153 e:000152 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/request_pattern.rb:143
c:0029 p:0074 s:0148 e:000147 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/request_pattern.rb:37
c:0028 p:0016 s:0142 e:000141 BLOCK  /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:58 [FINISH]
c:0027 p:---- s:0138 e:000137 IFUNC 
c:0026 p:---- s:0135 e:000134 CFUNC  :each
c:0025 p:---- s:0132 e:000131 CFUNC  :detect
c:0024 p:0021 s:0128 e:000127 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:57
c:0023 p:0012 s:0123 e:000122 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:50
c:0022 p:0074 s:0117 e:000116 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/http_lib_adapters/net_http.rb:79
c:0021 p:0015 s:0106 e:000105 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:1
c:0020 p:0044 s:0101 e:000100 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:7
c:0019 p:0256 s:0088 e:000087 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59
c:0018 p:0155 s:0079 e:000078 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164
c:0017 p:0014 s:0070 e:000069 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:579
c:0016 p:0014 s:0065 e:000064 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:526
c:0015 p:0016 s:0060 e:000059 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/element.rb:199
c:0014 p:0013 s:0056 e:000055 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/selenium/node.rb:148
c:0013 p:0013 s:0051 e:000050 BLOCK  /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/node/element.rb:269
c:0012 p:0052 s:0048 e:000047 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/node/base.rb:81
c:0011 p:0011 s:0040 e:000039 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/node/element.rb:269
c:0010 p:0338 s:0036 e:000035 METHOD /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/queries/selector_query.rb:84
c:0009 p:0013 s:0028 e:000027 BLOCK  /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/result.rb:29 [FINISH]
c:0008 p:---- s:0024 e:000023 IFUNC 
c:0007 p:---- s:0021 e:000020 CFUNC  :each
c:0006 p:---- s:0018 e:000017 CFUNC  :each
c:0005 p:---- s:0015 e:000014 IFUNC 
c:0004 p:---- s:0012 E:001fe0 CFUNC  :each
c:0003 p:---- s:0009 e:000008 CFUNC  :each
c:0002 p:---- s:0006 E:001770 IFUNC 
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/bin/cucumber:0:in `each'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/bin/cucumber:0:in `each'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/bin/cucumber:0:in `each'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/bin/cucumber:0:in `each'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/result.rb:29:in `block in initialize'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/queries/selector_query.rb:84:in `matches_filters?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/node/element.rb:269:in `visible?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/node/base.rb:81:in `synchronize'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/node/element.rb:269:in `block in visible?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/capybara-2.17.0/lib/capybara/selenium/node.rb:148:in `visible?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/element.rb:199:in `displayed?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:526:in `element_displayed?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:50:in `response_for_request'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:57:in `request_stub_for'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:57:in `detect'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:57:in `each'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/request_pattern.rb:37:in `matches?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/request_pattern.rb:143:in `matches?'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/util/uri.rb:37:in `variations_of_uri_as_strings'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/util/uri.rb:33:in `normalize_uri'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/webmock-3.2.1/lib/webmock/util/uri.rb:20:in `block in <class:URI>'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:2134:in `normalize'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1501:in `normalized_path'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1501:in `map'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1502:in `block in normalized_path'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:534:in `normalize_component'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:534:in `dup'
/home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:534:in `initialize_dup'

-- Machine register context ------------------------------------------------
 RIP: 0x000008b600000000 RBP: 0x0000000000a4af50 RSP: 0x00007f688a976158
 RAX: 0x00007f688a976208 RBX: 0x00007f676473d400 RCX: 0x0000000000000000
 RDX: 0x0000000000a4ab50 RDI: 0x00007f688a976208 RSI: 0x00007f686e3a2fc0
  R8: 0x0000000000000000  R9: 0x000000000ab288f0 R10: 0x0000000000000008
 R11: 0x0000000000000246 R12: 0x0000000005480000 R13: 0x0000000005480198
 R14: 0x000000000b395580 R15: 0x00007f688a976188 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
Received 'segmentation fault' signal
```

**Comment by dentarg** [comment]
@bmulholland what does the code that calls addressable look like? what's the input? I think you need to create a repro for this

**Comment by dentarg** [comment]
> /home/circleci/coupa_clm/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/lib/addressable/uri.rb:534: [BUG] Segmentation fault at 0x000008b600000000

Just dumping a link to that line: https://github.com/sporkmonger/addressable/blob/addressable-2.5.2/lib/addressable/uri.rb#L534

**Comment by sporkmonger** [comment]
Yeah, happy to investigate if we have a repro, even if it's fuzzed, but not sure there's much to do without one.

**Comment by bmulholland** [comment]
Alright, thank you both. I'll close this until I can get a repro.
