### ISSUE TITLE
Getting 'Invalid character in host' - cannot see what is wrong with host

### ISSUE THREAD

**Issue by vcavallo** [sporkmonger/addressable#316]
I've just deployed a skeleton app to Heroku which is working fine locally. Upon visiting the heroku app for the first time I get the following error:

```
2018-10-03T01:30:07.355811+00:00 app[web.1]: I, [2018-10-03T01:30:07.355598 #22]  INFO -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] Started GET "/lawyers.json" for 68.224.196.36 at 2018-10-03 01:30:07 +0000
2018-10-03T01:30:07.358617+00:00 app[web.1]: F, [2018-10-03T01:30:07.358536 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd]
2018-10-03T01:30:07.358748+00:00 app[web.1]: F, [2018-10-03T01:30:07.358679 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] Addressable::URI::InvalidURIError (Invalid character in host: 'https://people-protector-staging.herokuapp.com'):
2018-10-03T01:30:07.358835+00:00 app[web.1]: F, [2018-10-03T01:30:07.358773 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd]
2018-10-03T01:30:07.358986+00:00 app[web.1]: F, [2018-10-03T01:30:07.358898 #22] FATAL -- : [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:2438:in `validate'
2018-10-03T01:30:07.358989+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/addressable-2.5.2/lib/addressable/uri.rb:1128:in `host='
2018-10-03T01:30:07.358991+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:77:in `new_url'
2018-10-03T01:30:07.358993+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:53:in `headers'
2018-10-03T01:30:07.358994+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host/redirect.rb:32:in `response'
2018-10-03T01:30:07.358996+00:00 app[web.1]: [99add6df-2ac1-45d4-a10d-aa8b592fe4fd] vendor/bundle/ruby/2.5.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host.rb:21:in `call'

[ remainder trimmed]
```

The host is `https://people-protector-staging.herokuapp.com/lawyers.json` ... I can't see what is possibly wrong with this URI. The same issue arises when requesting the root URL.

Thanks!

**Comment by vcavallo** [comment]
See https://github.com/thoughtbot/suspenders/issues/940 for details on why I'm closing this.
Short story: I am very silly and Addressable is not broken at all :)
