### ISSUE TITLE
`heuristic_parse` parses two URLs as one

### ISSUE THREAD

**Issue by ahwatts** [sporkmonger/addressable#435]
After updating `addressable` to get a fix for `public_suffix`, it appears that the `heuristic_parse` method now happily parses two URLs separated by " or ":

```
awatts@ironic-mullet addressable [main %=] $ irb -Ilib
irb(main):001:0> require 'addressable/uri'
=> true
irb(main):002:0> Addressable::URI.heuristic_parse('http://example.com or http://example.com/2')
=> #<Addressable::URI:0xb4 URI:http://example.com%20or%20http//example.com/2>
irb(main):003:0> 
```

Previously, it would raise an exception in this case:

```
awatts@ironic-mullet addressable [(f02e386...) %] $ irb -Ilib
irb(main):001:0> require 'addressable/uri'
=> true
irb(main):002:0> Addressable::URI.heuristic_parse('http://example.com or http://example.com/2')
Traceback (most recent call last):
       10: from /home/awatts/.rbenv/versions/2.7.4/bin/irb:23:in `<main>'
        9: from /home/awatts/.rbenv/versions/2.7.4/bin/irb:23:in `load'
        8: from /home/awatts/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        7: from (irb):2
        6: from /home/awatts/Work/addressable/lib/addressable/uri.rb:203:in `heuristic_parse'
        5: from /home/awatts/Work/addressable/lib/addressable/uri.rb:135:in `parse'
        4: from /home/awatts/Work/addressable/lib/addressable/uri.rb:135:in `new'
        3: from /home/awatts/Work/addressable/lib/addressable/uri.rb:798:in `initialize'
        2: from /home/awatts/Work/addressable/lib/addressable/uri.rb:2305:in `defer_validation'
        1: from /home/awatts/Work/addressable/lib/addressable/uri.rb:2386:in `validate'
Addressable::URI::InvalidURIError (Invalid character in host: 'example.com or http')
irb(main):003:0> 
```

It appears that the change that introduced this was https://github.com/sporkmonger/addressable/commit/3a6b91c4660b4c01d548652c34a8363c82a1f4ea .

I think this is a bug, as that's clearly not a valid (single) URL, but given the comment here: https://github.com/sporkmonger/addressable/commit/3a6b91c4660b4c01d548652c34a8363c82a1f4ea#diff-831b213e8c4e581a6b683edba10e28c446b5b9db581fbdca650286aa7a486db7R5947-R5948 , maybe it shouldn't be? If I type that "url" in to Firefox, it does do a web search, but it's also not a valid (single) URL.

**Comment by dentarg** [comment]
What versions of Addressable are you using?

**Comment by dentarg** [comment]
> Previously, it would raise an exception in this case:

Okay, this is happening with Addressable 2.4.0

**Comment by ahwatts** [comment]
The old version of Addressable was 2.4.0, and I updated to 2.8.0.

**Comment by dentarg** [comment]
I don't think there's a bug here, looks to me that the change made in https://github.com/sporkmonger/addressable/commit/3a6b91c4660b4c01d548652c34a8363c82a1f4ea was intentional to make `heuristic_parse` behave in this way. It was [noted in the changelog](https://github.com/sporkmonger/addressable/blob/f3fb80c0adb60ce7012c36e5d3714b037a280b06/CHANGELOG.md#addressable-250): "`heuristic_parse` now trims whitespace before parsing"

`Addressable::URI.parse` still raises that error:

```
$ ruby -Ilib -raddressable/uri -e "p Addressable::VERSION::STRING; Addressable::URI.parse('http://example.com or http://example.com/2')"
"2.8.0"
/Users/dentarg/src/addressable/lib/addressable/uri.rb:2507:in `validate': Invalid character in host: 'example.com or http' (Addressable::URI::InvalidURIError)
	from /Users/dentarg/src/addressable/lib/addressable/uri.rb:2421:in `defer_validation'
	from /Users/dentarg/src/addressable/lib/addressable/uri.rb:840:in `initialize'
	from /Users/dentarg/src/addressable/lib/addressable/uri.rb:147:in `new'
	from /Users/dentarg/src/addressable/lib/addressable/uri.rb:147:in `parse'
	from -e:1:in `<main>'
``` 

We have now had this behaviour for almost ~5 years. I don't think it should be changed back.

**Comment by dentarg** [comment]
If you want to find the two URLs you could use the nice wrapper gem [twingly-url](https://github.com/twingly/twingly-url):

```shell
$ ruby -rtwingly/url/utilities -e 'p Twingly::URL::Utilities.extract_valid_urls("http://example.com or http://example.com/2").map(&:to_s)'
["http://example.com", "http://example.com/2"]
```
