### ISSUE TITLE
Semantic Versioning Issue

### ISSUE THREAD

**Issue by redxeagle** [sporkmonger/addressable#476]
With version 2.8.1 a breaking change was introduced.

The runtime reference to public_suffix  was changed to support also the version 5 of public_suffix 
(>= 2.0.2, < 6.0)

public suffix needs ruby version 2.6 minimum. 

Addressable in version 2.8.1. would still run in 2.2, but with this runtime dependency it isn't.

Thats why the gem git in version 1.12. can not be installed anymore lower for ruby version lower as 2.6.

Took us a while to figure this out.

**Comment by dentarg** [comment]
How are you installing addressable? If you use Bundler, it should install a version`public_suffix` that you can use:

```bash
$ docker run --rm -it -v $PWD:/app -w /app ruby:2.2 bash
root@ff722d3a6021:/app# ruby -v
ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-linux]
root@ff722d3a6021:/app# gem -v
2.7.6
root@ff722d3a6021:/app# bundle -v
Bundler version 1.16.1
root@ff722d3a6021:/app# cat public_suffix.gemfile
source "https://rubygems.org"
gem "public_suffix"
root@ff722d3a6021:/app# BUNDLE_GEMFILE=public_suffix.gemfile bundle install
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.16.1
Fetching public_suffix 3.1.1
Installing public_suffix 3.1.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
root@ff722d3a6021:/app#
root@ff722d3a6021:/app# cat addressable.gemfile
source "https://rubygems.org"
gem "addressable"
root@ff722d3a6021:/app# BUNDLE_GEMFILE=addressable.gemfile bundle install
Fetching gem metadata from https://rubygems.org/....
Resolving dependencies...
Using public_suffix 3.1.1
Fetching addressable 2.8.1
Installing addressable 2.8.1
Using bundler 1.16.1
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
```

---

With that said, there actually was just a brief period where bundler installed public_suffix 5.0.0 for me when I tried it on Ruby 2.4 (and Ruby 2.5).

```bash
$ bundle
Fetching gem metadata from https://rubygems.org/....
Resolving dependencies...
Fetching public_suffix 5.0.0
Installing public_suffix 5.0.0
Fetching addressable 2.8.1
Installing addressable 2.8.1
Using bundler 1.17.2
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ bundle exec ruby -raddressable -e 'p Addressable::VERSION::STRING'
/Users/dentarg/.gem/ruby/2.4.10/gems/public_suffix-5.0.0/lib/public_suffix.rb:12:in `require_relative': /Users/dentarg/.gem/ruby/2.4.10/gems/public_suffix-5.0.0/lib/public_suffix/rule.rb:224: syntax error, unexpected ']' (SyntaxError)
  new(value: content.to_s[2..], private: private)
                              ^
/Users/dentarg/.gem/ruby/2.4.10/gems/public_suffix-5.0.0/lib/public_suffix/rule.rb:272: syntax error, unexpected ']'
  new(value: content.to_s[1..], private: private)
                              ^
/Users/dentarg/.gem/ruby/2.4.10/gems/public_suffix-5.0.0/lib/public_suffix/rule.rb:302: syntax error, unexpected ']'
        @value.split(DOT)[1..]
                              ^
/Users/dentarg/.gem/ruby/2.4.10/gems/public_suffix-5.0.0/lib/public_suffix/rule.rb:350: syntax error, unexpected end-of-input, expecting keyword_end
  from /Users/dentarg/.gem/ruby/2.4.10/gems/public_suffix-5.0.0/lib/public_suffix.rb:12:in `<top (required)>'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/dentarg/.gem/ruby/2.4.10/gems/addressable-2.8.1/lib/addressable/uri.rb:22:in `<top (required)>'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/dentarg/.gem/ruby/2.4.10/gems/addressable-2.8.1/lib/addressable.rb:3:in `<top (required)>'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
  from /Users/dentarg/.rubies/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
```

**Comment by dentarg** [comment]
Also, CI is running successfully on Ruby 2.2 and up, I don't think any breaking change has been made.

**Comment by redxeagle** [comment]
I am not sure. 
We are not using bundler, simple plain install behavior. 
So a gem install addressable fail because of SemVer it try to install the highest available package of public suffix. and this is 5.0. which is not compatible.

**Comment by dentarg** [comment]
Well, isn't that the life of using old shit?

Sure, it doesn't work using old RubyGems

```bash
root@35ee80890621:/app# ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
root@35ee80890621:/app# gem -v
3.0.3
root@35ee80890621:/app# gem install git
Fetching addressable-2.8.1.gem
Fetching git-1.12.0.gem
Fetching public_suffix-5.0.0.gem
Fetching rchardet-1.8.0.gem
ERROR:  Error installing git:
	The last version of public_suffix (>= 2.0.2, < 6.0) to support your Ruby & RubyGems was 4.0.7. Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again
	public_suffix requires Ruby version >= 2.6. The current ruby version is 2.3.8.459.
```

After updating RubyGems (`gem update --system`) it does work

```bash
root@35ee80890621:/app# gem -v
3.3.21
root@35ee80890621:/app# gem install git
Fetching public_suffix-4.0.7.gem
Successfully installed rchardet-1.8.0
Successfully installed public_suffix-4.0.7
Successfully installed addressable-2.8.1
Successfully installed git-1.12.0
4 gems installed
```
