### ISSUE TITLE
Disallow tilde in host

### ISSUE THREAD

**Issue by greenfork** [sporkmonger/addressable#511]
The tilde symbol (`) seems allowed in the host. In [the spec](https://www.rfc-editor.org/rfc/rfc3986#appendix-A) it is not allowed:

```
host          = IP-literal / IPv4address / reg-name
reg-name      = *( unreserved / pct-encoded / sub-delims )
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
```

```ruby
require "addressable"

Addressable::URI.parse("htttp://`www.example.com")
#=> #<Addressable::URI:0x3c URI:htttp://`www.example.com>
```

**Comment by dentarg** [comment]
Yeah this looks like a bug

`uri` blows up on it:

```
irb(main):004:0> URI.parse("http://`www.example.com")
/Users/dentarg/.rubies/3.2.2/lib/ruby/3.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): "http://`www.example.com" (URI::InvalidURIError)
	from /Users/dentarg/.rubies/3.2.2/lib/ruby/3.2.0/uri/rfc3986_parser.rb:71:in `parse'
	from /Users/dentarg/.rubies/3.2.2/lib/ruby/3.2.0/uri/common.rb:193:in `parse'
	from (irb):4:in `<main>'
	from /Users/dentarg/.rubies/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /Users/dentarg/.rubies/3.2.2/bin/irb:25:in `load'
	from /Users/dentarg/.rubies/3.2.2/bin/irb:25:in `<main>'
```
