### ISSUE TITLE
Normalize errors when trying to run a simple url normalize

### ISSUE THREAD

**Issue by ck250186** [sporkmonger/addressable#513]
Addressable version: 2.8.4
Ruby version: 3.1.4

Code:

```
 require "addressable/uri"

 url = "https://google.com/cloud/storage"
 addressable_url = Addressable::URI.parse url

 po addressable_url.normalize.to_s
```

Error
```
Uncaught exception: Can't convert Object into String.
	/Users/chiragkanase/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/addressable-2.8.4/lib/addressable/uri.rb:1636:in `query='
	/Users/chiragkanase/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/addressable-2.8.4/lib/addressable/uri.rb:851:in `block in initialize'
	/Users/chiragkanase/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2392:in `defer_validation'
	/Users/chiragkanase/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/addressable-2.8.4/lib/addressable/uri.rb:840:in `initialize'
	/Users/chiragkanase/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2168:in `new'
	/Users/chiragkanase/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2168:in `normalize'
```

Is this a known issue?

**Comment by dentarg** [comment]
Sounds very much like https://github.com/sporkmonger/addressable/issues/506

Are you sure you haven't loaded other gems when you get the error?
